### PR TITLE
Making core work with Xcode

### PR DESCRIPTION
**Pull request by albertofustinoni**

### CODE REVIEW

**Comment by twinaphex** [comment]
What about MSVC? Will it fail to compile with this?

**Comment by albertofustinoni** [comment]
Yes, it does work for me in MSVC (2019) with the changes.

**Comment by irixxxx** [comment]
The change to pico/32x/memory.c isn't needed anymore.
However, if you're still out there, could you elaborate why that additional libretro-common stuff is necessary for you?
I've compiled standalone OSX builds with SDL without much fuss (no libretro version though), hence I'm a bit baffled.

**Comment by irixxxx** [comment]
hey @twinaphex, the changes outside of platform/libretro are IMO all obsolete. That leaves the changes to platform/libretro. Do you think those are OK? If so, this can go in.

**Comment by irixxxx** [comment]
@albertofustinoni this has been lying around far too long... would it be possible for you to check if this is still needed for you? The current master is compiling on osx for me.

**Comment by irixxxx** [comment]
Closed this as I believe this is already working in current master

**Pull request closed without merging**
