### PR TITLE
Add preliminary support for Demons of Asteborg

### PR DESCRIPTION
**Pull request by pjft**
This change adds preliminary support for Demons of Asteborg, a new game that was just released. More info here: https://www.demonsofasteborg.com/

Similar to what I just submitted for lr-genesis-plus-gx.

Specifically, I added header detection to use SSF2 mapper, per the developer's guidance (@Infitek).

What is missing now is SRAM support, which I don't believe is working for SSF2 either. Would appreciate guidance if I am to try to implement it myself, though the game seems to load for now with these changes. Unsure if I should add "prop = no_sram", let me know if that should be there and I'm happy to update. Game seemed to work the same way with and without it.

Thanks.

### CODE REVIEW

**Comment by twinaphex** [comment]
> What is missing now is SRAM support, which I don't believe is working for SSF2 either. Would appreciate guidance if I am to try to implement it myself, though the game seems to load for now with these changes. Unsure if I should add "prop = no_sram", let me know if that should be there and I'm happy to update. Game seemed to work the same way with and without it.

Hi, Picodrive libretro has a dedicated maintainer who can probably help you with this. 

@irixxxx you interested in the above? On that same note, can we merge this?

**Comment by pjft** [comment]
Apologies to both. Apparently the "not working" status was because of a faulty ROM that was sent over earlier, so it's the same with the lr-genesis-plus-gx PR. Restarting from the current master works as intended.

That being said, the game does load, but SRAM does not seem to be supported. I'll happily take guidance on it @irixxxx if you have suggestions.

@infitek details around SRAM use in the game would be helpful here. Thanks.

**Comment by irixxxx** [comment]
Just out of curiosity: what's the reason for canning this?

**Comment by pjft** [comment]
Thanks.

The changes I had originally made were done to support a ROM version that turned out to be faulty. The final version the developer released works out of the box with lr-picodrive, so I didn't want to have people merge things by mistake, or until further evidence suggests that these were actually needed. Apologies for the trouble!

That being said, SRAM support is not available. I tried to edit the SRAM ranges in the carthw file, but that didn't help in this case, and I lack the know-how to work that out.

**Pull request closed without merging**
